dev:
  tags:
    - meao
    - aws
  only:
    - gitlab
    - master
  variables:
    NAMESPACE: snippets-dev
  script:
    - bin/build_images.sh
    - bin/flake8.sh
    - bin/push2dockerhub.sh
    # no snippets-dev namespace in frankfurt currently
    # uncomment when mozmeao/infra#1120 is closed
    # - CLUSTER_NAME=frankfurt bin/update-config.sh
    - CLUSTER_NAME=oregon-b bin/update-config.sh
    

stage:
  tags:
    - meao
    - aws
  only:
    - stage
  variables:
    NAMESPACE: snippets-stage
  script:
    - bin/build_images.sh
    - bin/flake8.sh
    - bin/push2dockerhub.sh
    # no snippets-stage namespace in frankfurt currently
    # uncomment when mozmeao/infra#1120 is closed
    # - CLUSTER_NAME=frankfurt bin/update-config.sh
    - CLUSTER_NAME=oregon-b bin/update-config.sh


prod:
  tags:
    - meao
    - aws
  only:
    - prod
  variables:
    NAMESPACE: snippets-prod
  script:
    - bin/build_images.sh
    - bin/flake8.sh
    - bin/push2dockerhub.sh
    - CLUSTER_NAME=frankfurt bin/update-config.sh
    - CLUSTER_NAME=oregon-b bin/update-config.sh


admin:
  tags:
    - meao
    - aws
  only:
    - admin
    - prod
  variables:
    NAMESPACE: snippets-admin
  script:
    - bin/build_images.sh
    - bin/push2dockerhub.sh
    # no snippets-admin namespace in frankfurt currently
    # uncomment when mozmeao/infra#1120 is closed
    # - CLUSTER_NAME=frankfurt bin/update-config.sh
    - CLUSTER_NAME=oregon-b bin/update-config.sh
