stages:
  - build
  - test
  - deploy

build-images:
  stage: build
  tags:
    - meao
  script:
    - bin/build_images.sh
    - bin/push2dockerhub.sh

check-migrations:
  stage: test
  tags:
    - meao
  script:
    - ./manage.py makemigrations  | grep "No changes detected"

run-flake8:
  stage: test
  tags:
    - meao
  script:
    - bin/flake8.sh

run-unit-tests:
  stage: test
  tags:
    - meao
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  script:
    - bin/coverage-tests.sh

.deploy:
  stage: deploy
  tags:
    - meao
    - aws
  script:
    - bin/update-config.sh

dev:
  extends: .deploy
  only:
    - master
  variables:
    NAMESPACE: snippets-dev
    CLUSTERS: oregon-b

stage:
  extends: .deploy
  only:
    - stage
  variables:
    NAMESPACE: snippets-stage
    CLUSTERS: oregon-b

admin:
  extends: .deploy
  only:
    - admin
  variables:
    NAMESPACE: snippets-admin
    CLUSTERS: oregon-b

prod:
  extends: .deploy
  only:
    - prod
  variables:
    NAMESPACE: snippets-prod
    CLUSTERS: frankfurt oregon-b
