variables:
  DOCKER_REPOSITORY: "mozorg/snippets"
  DOCKER_IMAGE_TAG: "${DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}"
  # Cannot use $DOCKER_IMAGE_TAG because it contains other variables itself.
  DOCKER_RUN_CMD: "docker run --env-file .docker-env ${DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}"

stages:
  - build
  - test
  - deploy

build-images:
  stage: build
  tags:
    - meao
  script:
    - bin/build_images.sh
    - docker push ${DOCKER_IMAGE_TAG}

.test-stage:
  stage: test
  variables:
    DEBUG: "False"
    ALLOWED_HOSTS: "*"
    SECRET_KEY: "foo"
    DATABASE_URL: "sqlite:///"
    SITE_URL: "http://localhost:8000"
    CACHE_URL: "dummy://"
    ENABLE_ADMIN: "True"
    SECURE_SSL_REDIRECT: "False"
  before_script:
    - env > .docker-env

check-migrations:
  extends: .test-stage
  tags:
    - meao
  script:
    - ${DOCKER_RUN_CMD} bash -c './manage.py makemigrations  | grep "No changes detected"'

run-flake8:
  extends: .test-stage
  tags:
    - meao
  script:
    - ${DOCKER_RUN_CMD} flake8 snippets

run-unit-tests:
  extends: .test-stage
  tags:
    - meao
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  script:
    - ${DOCKER_RUN_CMD} bash -c 'coverage run ./manage.py test --parallel; coverage report'

.deploy:
  stage: deploy
  tags:
    - meao
    - aws
  script:
    - bin/update-config.sh

dev:
  extends: .deploy
  only:
    - master
  variables:
    NAMESPACE: snippets-dev
    CLUSTERS: oregon-b

stage:
  extends: .deploy
  only:
    - stage
  variables:
    NAMESPACE: snippets-stage
    CLUSTERS: oregon-b

admin:
  extends: .deploy
  only:
    - admin
  variables:
    NAMESPACE: snippets-admin
    CLUSTERS: oregon-b

prod:
  extends: .deploy
  only:
    - prod
  variables:
    NAMESPACE: snippets-prod
    CLUSTERS: frankfurt oregon-b
