sudo: required
services:
  - docker
language: python
before_install:
  - docker --version
install:
  - CI_COMMIT_SHORT_SHA=latest make pull
  - make build
script:
  - make lint
  - make check-migrations
  - make test
